### ISSUE TITLE
Unifi controller update

### ISSUE THREAD

**Issue by off14** [wvengen/unifi-controllable-switch#7]
As ubiquity doesn't want to update the firmware officially, any chance to get a custom update for their controller to support tough switches with modified firmware?
e.g. create a 5port tough switch in controller instead of using existing 8port-60wpoe

**Comment by wvengen** [comment]
That would be possible in theory. But the model types seem to be spread all over the place (try grepping). It might technically be possible to decompile the jar, apply patches, and recompile, but that's a serious effort - and may need changing on every controller update. The result is probably not redistributable.
Perhaps I'd rather rewrite the controller as an open source project, that would be more useful, I think. Probably a bigger effort, though.

You already see 5 ports in most overviews with the official controller (properties panel, and switch statistics), even though the model name is wrong.
